### ISSUE TITLE
Assign key from person page, then click edit

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#1037]
When assigning an existing serial from the person page, this doesn't do anything.
Maybe hide it?
Don't worry because most people will not do that?

![image](https://user-images.githubusercontent.com/469010/94941252-7c74eb80-0489-11eb-9def-a5c8a622c493.png)

**Comment by srkirkland** [comment]
@jSylvestre @wongband Didn't this get fixed?

**Comment by wongband** [comment]
I don't believe so

**Comment by jSylvestre** [comment]
It still does nothing.
