### ISSUE TITLE
Group Person Access?

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#1046]
We’re now having the DiSSC team enter the “People” in PEAKS. (DiSSC is now supported by us, BTW.) The issue we have is of course that 1) not all clusters in the college are on PEAKS and 2) we’ll need some way to grant all the DiSSC staff access to all the teams in CA&ES. :hmmm:
12:35
I’m pushing on 1 but will need help on 2.
12:36
For 2, permissions on a “team of teams” would be nice.

**Comment by srkirkland** [comment]
group feature of reporting is sufficient
