### ISSUE TITLE
Assigning Access dup display

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#1086]
If you open an access, and assign a person, then assign another person without refreshing, they appear multiple times:
![image](https://user-images.githubusercontent.com/469010/106318782-43753980-6225-11eb-9ac5-e80c014f664b.png)

**Comment by jcubbage** [comment]
Ooooohhhh....that's fun! Need model refresh after assignments. Do any of the other assets do that?

**Comment by jSylvestre** [comment]
> Ooooohhhh....that's fun! Need model refresh after assignments. Do any of the other assets do that?

No, all the others can only have 1 assignment
