### ISSUE TITLE
Dialog action buttons are off the screen.

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#1259]
Dialog action buttons are often off the bottom of the screen and users may not realize they need to scroll down to see them.
Perhaps we could have an "actions" area off to the side of the dialog for these?

![image](https://github.com/ucdavis/Peaks/assets/469010/d8732bfb-346f-4651-a0a6-d103304aecf4)

**Comment by laholstege** [comment]
@cydoval what do you think about this? it's easy to make the modal scrollable and keep the footer fixed, like: 
![image](https://github.com/ucdavis/Peaks/assets/27025973/2fdd0db7-97b0-48e7-9cc0-70613de43f08)
but would you rather have them off to the side? or somewhere else?

**Comment by jSylvestre** [comment]
Does the dialog fit to the window, or on a smaller screen would there also be a scroll bar on the browser window?

**Comment by laholstege** [comment]
@jSylvestre there's a scrollbar on a smaller screen (horizontal as well, actually. which exists without `scrollable = true` but isn't visible)
for example, what it looks like currently 
![image](https://github.com/ucdavis/Peaks/assets/27025973/42816677-ec13-424a-befc-168ef51f04a0)
vs with scrollable (though i have to fiddle with the css a small amount) 
![image](https://github.com/ucdavis/Peaks/assets/27025973/08fbc000-ff8f-442c-912e-33be01fff889)
