### ISSUE TITLE
Completed Documents Reporting in Group

### ISSUE THREAD

**Issue by acgetchell** [ucdavis/Peaks#1307]
In CAES group, need to be able to view a report of all completed Docusigned documents (e.g. CAES IT Resource Guidelines)

**Comment by jSylvestre** [comment]
@acgetchell Do you mean one like is available in the team? 

![image](https://github.com/ucdavis/Peaks/assets/469010/b9bc7090-2b80-4e9b-bed9-4b728964fb1f)
