### ISSUE TITLE
Adding item

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#356]
I did this with a key, but it probably applies to all assets.
When I add a new key, and there are already more than one page, it stay on the current page instead of going to the last page which displays the newly added item

**Comment by laholstege** [comment]
@jSylvestre @srkirkland do we still want to do this? doesn't look like there's an easy way to do this via react-table. i could add new items to the front of arrays?

**Comment by jSylvestre** [comment]
@laholstege No one has requested it, so feel free to close it.
