### ISSUE TITLE
History Report

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#482]
So, I don't know that we want to do this, it is just a thought...

The history only shows that last 5 or so entries, so we could do a report for all the places in React that we list the history to expand that.

Also, access is currently not displaying a history, but it is being saved.

**Comment by jcubbage** [comment]
Could we have a button that says "load full history", then update all the GetHistory to include optional bool that loads all instead of 5?

**Comment by jSylvestre** [comment]
This might be challenging.  The history table doesn't have a team id.

**Comment by srkirkland** [comment]
If there are 5 entries (or maybe always), have button which opens a new window showing full history of item
