### ISSUE TITLE
Key Serials SN

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#491]
Should the SN of a key serial be editable?
Should we allow a key serial to be deleted?
Should we add a status like Error (if the wrong serial was entered and we don't allow it to be changed or deleted)

**Comment by jcubbage** [comment]
@jSylvestre I think this is complete: We allow SN of key to be edited. We don't allow delete, but do have notes and "destroyed" as status.

**Comment by jSylvestre** [comment]
@jcubbage Yes, but I'm asking if we "should" allow this.
