### ISSUE TITLE
Bigfix Integration?

### ISSUE THREAD

**Issue by jcubbage** [ucdavis/Peaks#501]
Need to get API key for Bigfix for the team. Then, can lookup equipment in big fix -

**Comment by jcubbage** [comment]
![image](https://user-images.githubusercontent.com/599659/52822272-0f1f0780-3066-11e9-905c-cc3eef1ea134.png)

**Comment by srkirkland** [comment]
We now have API access to CAES at least.  API info:

https://bigfix-master1.ou.ad3.ucdavis.edu:52311/api/help

docs: 
https://developer.bigfix.com/rest-api/
https://developer.bigfix.com/rest-api/gettingstarted.html

**Comment by srkirkland** [comment]
useful links:
https://bigfix-master1.ou.ad3.ucdavis.edu:52311/api/computer/58350692/settings
https://bigfixwebui.ucdavis.edu
https://bigfixreports.ucdavis.edu/webreports?page=SingleComputerReport&ComputerName=UCD+BigFix/50977892&IsTranslated=1

**Comment by jcubbage** [comment]
![image](https://user-images.githubusercontent.com/599659/63540122-5af8b080-c4d0-11e9-891d-2370688233fc.png)

**Comment by srkirkland** [comment]
BigFix Integration:

In the equipment details/edit popup, if the "bigfixID" field has a value, then add a little "info" icon (similar to protection level above).  Once clicked, this should pop up another modal which will call the BigFix API to display additional read-only information about that computer (service: https://github.com/ucdavis/Peaks/blob/master/Keas.Mvc/Services/BigfixService.cs).
