### ISSUE TITLE
Automate PPS import

### ISSUE THREAD

**Issue by jcubbage** [ucdavis/Peaks#542]
So departments don't have to keep doing this. Weekly? Some setting to control?

**Comment by jSylvestre** [comment]
I'd say nay. But possible if we do the crazy on/off boarding email

**Comment by jcubbage** [comment]
We have a department requesting it be automated so they don't have to assign someone to go and hit PPS update every week.

**Comment by jSylvestre** [comment]
They have a dept where people are joining them every week?
Really, they should use this for the initial load, then the on boarding process should include adding the person. As any roll can add a person, it doesn't need the DA to do it.

**Comment by jcubbage** [comment]
Yeah! Crazy right. Department that has almost 800 people in it. People arrive and leave all the time.

**Comment by srkirkland** [comment]
Would need to be opt-in.  Should update existing people, add new people, and not remove missing people.

**Comment by srkirkland** [comment]
I'm going to punt on this too until we have a request for this feature but a user (or two)
