### ISSUE TITLE
Reporting Teams

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Peaks#545]
Need to create "super teams" which will be associated manyXmany to existing teams and filled with users who have a new permission in that team.  The purpose of reporting teams is to run a set of "overview" read-only reports which can span multiple teams, things like "how many computers are in these teams"?

Option 1 -- use the same Teams table and just have a bool for IsReporting.  Would allow us to reuse some of the existing teamPermissions.

Option 2 -- new terminology, something like ReportingGroup, which has its own permissions/tables and can associate with >= 1 team.

**Comment by jSylvestre** [comment]
Might cause some extra queries for auth. But if it is limited to reports shouldn't be too bad

**Comment by srkirkland** [comment]
Decision:

Flag on team to indicate if `IsReporting` type team, default false.

Bridge table for team (many -> many) back to teams, called ReportingTeams.

New role "ReportAdmin" which can't be added to team roles except by super admins, since we will be only people who can view team admin.

Modify access check attribute to check, if all else fails, if person is a ReportAdmin on any team that is a reporting type team and has the desired team as one of its children.

Possibly overload team chooser page to show teams in two categories, regular and report-only.

**Comment by jSylvestre** [comment]
If user chooses a super team, they are redirected to a new page to choose one of the sub teams.

**Comment by jSylvestre** [comment]
Ok, re-think.
* [ ] Create new table Groups
* [ ] Create join table from groups to teams
* [ ] Create admin pages to manage groups
* [ ] Routes will exclude group
* [ ] Choose teams page will have a choose group if available

**Comment by srkirkland** [comment]
@jSylvestre where did we get to on this?  I think you did make groups.  Just want it documented and to figure out what's next
