### ISSUE TITLE
Reports & API enhancements

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Peaks#546]
Need reports for at least each of PEAKS.  List my people, list equipment, list of workstations, etc.

API should also be extended to return the same information (or superset) as each report.  If possible, it would be great to even drive the report tables off of the API calls directly, since that'll give us parity between reports and the API.

**Comment by jcubbage** [comment]
- [ ] People - same as list() except replace counts with actual asset objects.

- [ ] Equipment - list()

- [ ] Access - list()

Keys:
