### ISSUE TITLE
Confirmation Page?

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#664]
At least for equipment, do we want to provide more info? Maybe just make and model?
Maybe do a help text that has more fields?
Any fields that we wouldn't want displayed? (Notes)

**Comment by jSylvestre** [comment]
FYI, this page could probably use more details:

![image](https://user-images.githubusercontent.com/469010/62562156-79567f00-b835-11e9-89cc-3d76da9388ef.png)

**Comment by laholstege** [comment]
put make/model in here
