### ISSUE TITLE
Docusign feature request

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#668]
I would like to request a new feature. Using Docusign API allow people inputting data to call for a document to be signed. The first example is when we enter and assign a cell phone we would like to have the person assigned sign the official UCOP cell phone policy document. https://www.ucop.edu/information-technology-services/services/ucop-it-services/work-equipment-computers-smartphones-software/files/device-usage-agreement.pdf

**Comment by jSylvestre** [comment]
INC0830787

**Comment by srkirkland** [comment]
Docusign API access: https://admindemo.docusign.com/
You have to develop the API access there and then get it approved to move to production.

**Comment by srkirkland** [comment]
@srkirkland Ask Adam and Shuka & Jeremy Philips about use cases. Maybe person-level instead of asset level?
