### ISSUE TITLE
New table for Equipment Attribute Key choices

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#706]
columns
- [x] id
- [x] teamId (nullable means global system)
- [x] Key
- [x] Key Description

- [x] Dept Admin can add values for their team
- [x] Equipment attributes key type ahead only allows global and team keys
- [x] Import ignores these and can import Anything?
- [x] Import warns if key doesn't match?
- [ ] Info icon that will list all key choices?
- [x] UI for team and or system to maintain keys
- [x] Populate global data with DbInit

**Comment by srkirkland** [comment]
Sounds good.  I think key description could be a cool thing to put in the typeahead and maybe even on a mouseover later.  Possibly we want to let equipment admins be able to setup attributes, but if that's hard then leave it for later.  Info icon listing all types or opening in a new window a types report could be a useful later feature
