### ISSUE TITLE
Bigfix Search

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#761]
Make the found computer "button" more clear that clicking on it will fill in the BF ID

**Comment by laholstege** [comment]
![image](https://user-images.githubusercontent.com/27025973/65709425-9fceb480-e045-11e9-9838-17081392adee.png)
@cydoval

**Comment by laholstege** [comment]
add h2 "Select a result below to assign bigfix id"
turn into list, each option <ul>
