### ISSUE TITLE
Add new person, search for Supervisor

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#765]
You can't do this on creating a new person, but I'm not sure what the UI should be:
(You can when editing a person)

![image](https://user-images.githubusercontent.com/469010/64995235-897b6880-d88f-11e9-9a2d-b0590a1ad563.png)

**Comment by laholstege** [comment]
this is happening because this link routes to `/people/create`, but we're already on that page. i can either add logic to handle resetting the state, or i can make this link just always open a new tab. thoughts @srkirkland ?
