### ISSUE TITLE
improvements to access

### ISSUE THREAD

**Issue by laholstege** [ucdavis/Peaks#813]
- have assignments table always be editable (currently revoking is greyed out except for on edit table)
- remove modal styles from details (green sidebar)
- improve styles on revoke modal
- see if you can have assigning from access details not take you back to the table
- have edit access and delete access buttons

**Comment by klanmiko** [comment]
@laholstege There's a separate issue I made that's the same so I'm moving the bullet points over.

I can make the assignments table always editable, except on the assign page itself

Do you know what you would like to see on the revoke modal?

Also I don't think any other asset type has a delete button in the details page.
