### ISSUE TITLE
put tags and filters into context

### ISSUE THREAD

**Issue by laholstege** [ucdavis/Peaks#817]

**Comment by srkirkland** [comment]
Have the asset controller return a list of the team's tags along with team info and permissions: https://github.com/ucdavis/Peaks/blob/master/Keas.Mvc/Controllers/AssetController.cs#L37.

Tags are pulled using the same code as the API does: https://github.com/ucdavis/Peaks/blob/master/Keas.Mvc/Controllers/Api/TagsController.cs#L27.

Then, on the asset homepage, set the tag array to some global var, say `window.App.tags`: https://github.com/ucdavis/Peaks/blob/master/Keas.Mvc/Views/Asset/Index.cshtml.

In the boot file, grab those tags and load them into React Context -- will require changing some types as well: https://github.com/ucdavis/Peaks/blob/master/Keas.Mvc/ClientApp/pages/assets/boot.tsx#L26.

Once that's all done, go through every typescript container and remove the calls to the api `api/team/tags/listTags` and remove tags from state entirely.  Any place the this.state.tags was used, get tags from context instead.
