### ISSUE TITLE
Get Title 

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#857]
From IAM should probably not throw an exception because we probably don't care that much...

**Comment by srkirkland** [comment]
@jSylvestre example of a person where this happens?

**Comment by jSylvestre** [comment]
@srkirkland I don't have an example of a person for this. I have a vague recollection Chris Derr mentioned it.
But, we can always wrap this in a try catch:
https://github.com/ucdavis/Peaks/blob/master/Keas.Mvc/Services/IdentityService.cs#L247

**Comment by srkirkland** [comment]
👍  Sure, let's wrap in a try/catch and log and return string.empty on fail
