### ISSUE TITLE
Table variance

### ISSUE THREAD

**Issue by cydoval** [ucdavis/Peaks#913]
<img width="718" alt="Screen Shot 2020-07-23 at 11 12 19 AM" src="https://user-images.githubusercontent.com/1899553/88322460-9a79df00-ccd5-11ea-83ce-48e31b301266.png">

**Comment by jSylvestre** [comment]
@cydoval Tables are changing new look will be something like this:

![image](https://user-images.githubusercontent.com/469010/88323103-8d112480-ccd6-11ea-9c52-cddf5d8c3e02.png)

**Comment by cydoval** [comment]
addressed in 2020design1 branch
