### ISSUE TITLE
Edit Access Routing.

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Peaks#995]
To edit access, you need to click on details.
When you click "Edit Access", the edit dialog appears, but behind that the page turns to the access list.

It should remain and update the details page

**Comment by wongband** [comment]
I noticed that the delete button does the same as well. Should we solve that problem as well?

**Comment by jSylvestre** [comment]
> I noticed that the delete button does the same as well. Should we solve that problem as well?

If you mean the delete the entire access, then no. If you mean delete someone assigned to an access, then probably yes.

**Comment by jSylvestre** [comment]
Also, there is a delete action from the list. Wouldn't want that messed up.
